Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "userapi-vm"

  # Sync the repo root
  config.vm.synced_folder "../", "/vagrant-root"

  # Sync only the app folder into /opt/userapi
  config.vm.synced_folder "../userapi/src/app", "/opt/userapi/src/app"

  # Expose API port
  config.vm.network "forwarded_port", guest: 8000, host: 8000

  # Provision using ansible_local inside the VM
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbooks/site.yml"
    ansible.install = true
  end
end
