Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "userapi-vm"

  # Synced folder: your app code goes into the VM
  config.vm.synced_folder "../userapi/src/app", "/opt/userapi"

  # Network
  config.vm.network "forwarded_port", guest: 8000, host: 8000

  # Provisioning via Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbooks/site.yml"
  end
end
